apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: faultcollections.programming.kubernetes.dev
spec:
  group: programming.kubernetes.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                description:
                  type: string
  scope: Namespaced
  names:
    plural: faultcollections
    singular: faultcollection
    kind: FaultCollection
    shortNames:
    - fc
---
apiVersion: "programming.kubernetes.dev/v1"
kind: FaultCollection
metadata:
  name: ecommerce
spec:
  description: ecommerce based collection of faults
---
apiVersion: "programming.kubernetes.dev/v1"
kind: FaultCollection
metadata:
  name: basic
spec:
  description: basic example
